# version: '3.8'

services:
  # Service Oracle Database
  oracle-db:
    image: container-registry.oracle.com/database/express:21.3.0-xe
    container_name: oracle-ticket-db
    ports:
      - "1521:1521"
      - "5500:5500"
    environment:
      - ORACLE_PWD=your_sys_or_system_pwd # system and sys
      - ORACLE_CHARACTERSET=AL32UTF8
    volumes:
      - oracle-data:/opt/oracle/oradata
      # Script d'initialisation pour créer les utilisateurs et schémas
      - ./init-scripts:/opt/oracle/scripts/startup
    healthcheck:
      test: ["CMD", "sqlplus", "-L", "sys/your_sys_or_system_pwd//localhost:1521/xepdb1 as sysdba", "@/opt/oracle/scripts/startup/healthcheck.sql"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 100s
    networks:
      - ticket-network

  # Service Spring Boot Application
  ticket-app:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: ticket-app
    ports:
      - "8089:8089"
    depends_on:
       - oracle-db
        #condition: service_healthy
    environment:
      # tns format
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@
        (DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=oracle-db)(PORT=1521))(CONNECT_DATA=(SERVICE_NAME=xepdb1)))
      - SPRING_DATASOURCE_USERNAME=ticket_user
      - SPRING_DATASOURCE_PASSWORD=ticket_password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=oracle.jdbc.driver.OracleDriver
      - SPRING_JPA_SHOW_SQL=true
      - JWT_SECRET=salimsaleysalimsaleysalimsaleysalimsaleysalimsaleysalimsaleysalimsaleysalimsaleysalimsaley
      - LOGGING_LEVEL_ROOT=INFO
      - LOGGING_LEVEL_COM_HAHN_TICKETSYSTEM=DEBUG
    networks:
      - ticket-network

volumes:
  oracle-data:
    driver: local

networks:
  ticket-network:
    driver: bridge